### PR TITLE
Use UmeFont instead of Source Han Sans Japanese

### PR DESCRIPTION
**Pull request by shimon1024**
## Description
cf. https://github.com/ValveSoftware/Proton/issues/5201

This patch mitigates a problem that characters were misaligned such as dialog text because they were used the wrong font. This patch replaces Source Han Sans Japanese by UmeFont[^1]. UmeFont is metric-compatible fonts with MS Japanese fonts[^2].

## Concerns

- UmeFont possibly lack some glyphs.
- On other games, Source Han Sans Japanese is possibly more suitable than UmeFont.
  - e.g.
    - [The GTA V installer](https://github.com/ValveSoftware/Proton/pull/5352#issuecomment-984480536)
- License. It seems like UmeFont license is compatible with DFSG[^3]. However, It seems like the list of OSI-approved licenses[^4] don't contain UmeFont license.
  - [resolved](https://github.com/ValveSoftware/Proton/pull/5352#issuecomment-984480536).
- UmeFont upstream is possibly inactive.

## Screenshots

<details><summary>Player Data</summary>

Without Ume:
th10_source_han_sans

With Ume:
th10_ume

Original (MS Gothic):
th10_playerdata_msgothic

</details>

<details><summary>Dialog</summary>

Without Ume:
th10_dialog_source_han_sans

With Ume:
th10_dialog_ume

Original (MS Gothic):
th10_dialog_msgothic

</details>

<details><summary>Spell card name</summary>

Without Ume:
th10_spellcard_source_han_sans

With Ume:
th10_spellcard_ume

th10_spellcard_msgothic

</details>

Ending scenes have the same problem, but screenshots isn't posted because of the guidelines[^5].

[^1]: https://ja.osdn.net/projects/ume-font/
[^2]: https://wiki.archlinux.org/title/Metric-compatible_fonts#Ume
[^3]: https://packages.debian.org/search?keywords=fonts-horai-umefont&searchon=names&suite=all&section=main
[^4]: https://opensource.org/licenses/alphabetical
[^5]: https://touhou-project.news/guidelines_en/

### CODE REVIEW

**Comment by aeikum** [comment]
Thanks for the PR.

> On other games, Source Han Sans Japanese is possibly more suitable than UmeFont

Do you know which games may work better with Source Han Sans? Or in what situations?

**Comment by shimon1024** [comment]
I don't know games or situations for which Source Hans Sans Japanese is suitable. This is a potential concern.

**Comment by giomasce** [comment]
I don't think the license is a big concern:
```
These fonts are free software.
Unlimited permission is granted to use, copy, and distribute it,
with or without modification, either commercially and noncommercially.
THESE FONTS ARE PROVIDED "AS IS" WITHOUT WARRANTY.
```
Very minimal, but I guess it's enough by our standards.

However, even with this PR applied, I am not seeing big differences in how text is aligned in the showcased game.

I also tested a couple of games on which I worked before to fix CJK support. The Cyberpunk 2077 launcher seems doing find with the Ume fonts patch applied. The GTA V installer shows some quality degradation, as if the new fonts doesn't properly support antialiasing, at least in some cases (the license text shown here is rendered with GDI by the richedit component).

**Without Ume**
without_ume

**With Ume**
with-ume

On the other hand, I can't see any missing glyphs. Don't know how much representative this text is of any other Japanese text.

I don't think it is particularly important that a one-time installer or a license text is formatted in a particularly eye-candy way, so that wouldn't be a stopper for me. But first I would at least understand better is the patch is actually bringing some enhancement to a game. So far I cannot see any.

**Comment by giomasce** [comment]
Actually, comparing two screenshot more attentively I found some differences:

**With Ume**
Schermata da 2021-12-02 11-14-29

**Without Ume**
Schermata da 2021-12-02 11-17-34

The screenshot with Ume shows a better aligned table, even though the first two lines are still a little bit off (that seems to be related to the fact that there are single instead of double digit numbers). But there are no Japanese glyphs, so the comparison is not very useful. How do I get Japanese characters in that table? Perhaps you could share some savefile that has them? Is that a high scores table?

**Comment by shimon1024** [comment]
Re: https://github.com/ValveSoftware/Proton/pull/5352#issuecomment-984480536

> I also tested a couple of games

Thanks for testing. 

> I don't think it is particularly important that a one-time installer or a license text is formatted in a particularly eye-candy way, so that wouldn't be a stopper for me.

The license text using Ume is difficult to read because some characters (such as `書` and `譲`) are squashed. Perhaps Source Han Sans is suitable than Ume about the GTA V license text for readability because the license text is a legal notice.

> But first I would at least understand better is the patch is actually bringing some enhancement to a game. So far I cannot see any.

For example, these screenshots[^1] indicate advantage of Ume.

[^1]: `Screenshots` of https://github.com/ValveSoftware/Proton/pull/5352#issue-1065072803

**Comment by shimon1024** [comment]
@giomasce Re: https://github.com/ValveSoftware/Proton/pull/5352#issuecomment-984493416

> Perhaps you could share some savefile that has them? Is that a high scores table?

savefile 1 (unplayed): [scoreth10.dat.tar.gz](https://github.com/ValveSoftware/Proton/files/7776745/scoreth10.dat.tar.gz)

<details><summary>screenshots of savefile 1:</summary>

With Ume:
th10_01_ume

Without Ume:
th10_01_source_han
</details>

savefile 2 (one spell card): [scoreth10.dat.tar.gz](https://github.com/ValveSoftware/Proton/files/7776748/scoreth10.dat.tar.gz)

<details><summary>screenshots of savefile 2:</summary>

With Ume:
th10_02_ume

Without Ume:
th10_02_source_han
</details>

savefile 3 (three spell cards): [scoreth10.dat.tar.gz](https://github.com/ValveSoftware/Proton/files/7776749/scoreth10.dat.tar.gz)

<details><summary>screenshots of savefile 3:</summary>

With Ume:
th10_03_ume

Without Ume:
th10_03_source_han
</details>

savefile 4 (high scores): [scoreth10.dat.tar.gz](https://github.com/ValveSoftware/Proton/files/7776750/scoreth10.dat.tar.gz)

<details><summary>screenshots of savefile 4:</summary>

With Ume:
th10_04_ume

Without Ume:
th10_04_source_han
</details>

> The screenshot with Ume shows a better aligned table, even though the first two lines are still a little bit off (that seems to be related to the fact that there are single instead of double digit numbers).

This is interesting. My screenshots with Ume shows a aligned table.

th10_01_ume

It seems like the Giovanni's screenshot with the Ume is not using the Ume for ASCII characters. `0` (zero) of the Ume (Ume Gothic) has a dot in the center. I don't know why the screenshot is not using the Ume for ASCII characters. Proton's version? Font settings? Locale settings? My locale is Japanese.

**Comment by giomasce** [comment]
Ok, setting locale to Japanese fixed my issues, so now I think I can wholly reproduce your improvements, and I agree that this game. As I said, I am not a lawyer, but I think that from the legal point of view we should be safe. So the only item left to be discussed is whether any game is impacted by this font change. It seems that GTA V has a few problems, though I don't expect gamers to care too much about whether the game's license is perfectly rendered or not.

**Comment by shimon1024** [comment]
Okay, I leave the decision about GTA V to Proton's developers. I agree that the only item left to be discussed is whether any game is impacted by this font change.

**Comment by shimon1024** [comment]
I added some screenshots to the first comment.

**Comment by zzhiyi** [comment]
Attack on Titan 2 進撃の巨人２ (601050) launcher missing reset and confirm buttons can be fixed by using Ume UI Gothic as MS UI Gothic.

**Comment by shimon1024** [comment]
I felt that the gaming experience is different between the UmeFont (this patch) and MS Gothic (original) when I compared the UmeFont, Source Han Sans, and MS Gothic in Touhou Fuujinroku.

I'm not a typography expert, but it seems that there are some differences between the UmeFont and MS Gothic glyphs.

- The UmeFont's hiragana, katakana, and some fullwidth punctuation glyphs are large compared to MS Gothic.
- The UmeFont's hiragana, katakana, and some fullwidth punctuation glyphs are more rounded than MS Gothic.

It seems that those features are on purpose because someone points out[^1] that the old glyphs of hiragana and katakana of the UmeFont are similar to MS Gothic.

[^1]: https://ja.osdn.net/projects/ume-font/lists/archive/info/2009-September/000230.html (In Japanese)

**Comment by giomasce** [comment]
I don't think it was mentioned here, but we plan to use Ume fonts for Japanese in Proton 7.0, unless testing reveals that they break something (so far it doesn't seem to be the case).

**Comment by shimon1024** [comment]
> I don't think it was mentioned here, but we plan to use Ume fonts for Japanese in Proton 7.0, unless testing reveals that they break something (so far it doesn't seem to be the case).

I got it. Thank you for the work of Proton's developers.

Proton cannot use real MS Gothic, so Proton needs a plan B. Maybe there are better ways than this patch (for example, blend the Ume fonts excluding hiragana and katakana, and the adjusted hiragana and katakana glyphs of Source Han Sans Japanese), but at least this patch mitigates the misalignment problem.

**Comment by simon-i1-h** [comment]
I have confirmed that this patch is applied[^1] on Proton 7.0-1. Thank you so much.

proton7 0-1

[^1]: https://github.com/ValveSoftware/Proton/commit/7a46a3cf4011ae3441cddff94d08bc280825a755

**Comment by shimon1024** [comment]
I have confirmed that this patch is applied[^1] on Proton 7.0-1. Thank you so much.

proton7 0-1

[^1]: https://github.com/ValveSoftware/Proton/commit/7a46a3cf4011ae3441cddff94d08bc280825a755

**Pull request closed without merging**
