### PR TITLE
proton: adding some titles as xalia compatible

### PR DESCRIPTION
**Pull request by vinifmor**
Adding the following titles as XALIA compatible:
- Oddworld: Stranger's Wrath HD (15750)
- The TakeOver (418620)

### CODE REVIEW

**Comment by madewokherd** [comment]
I did some work on Stranger's Wrath HD recently.

The Takeover causes Xalia to crash in my testing due to WriteProcessMemory failing.

**Comment by vinifmor** [comment]
@madewokherd I've just retested both and they are working on my end (AMD GPU, Mesa 24.2.3, Kernel 6.6, Plasma 6.1.5, X11 and Xwayland).

**Comment by alasky17** [comment]
@vinifmor Thank you for taking an interest in Xalia and highlighting some games that are improved with Xalia :) Folks took a look at Oddworld: Stranger's Wrath HD (15750) and Xalia has been enabled for that one in the most recent experimental release.  We are taking a look at The Takeover too :)  Since this PR is already out of date, I hope you don't mind me closing this so you don't need to take the effort to rebase? 

In the future, feel free to also comment on the game-specific github issues in this tracker and tag me and/or @kisak-valve and/or @madewokherd  if you notice any games that benefit from enabling Xalia.  You can also open issues here if you find any bugs https://github.com/madewokherd/xalia :)

**Comment by vinifmor** [comment]
Thank you for the feedback @alasky17  (:

**Comment by jams3223** [comment]
> @vinifmor Thank you for taking an interest in Xalia and highlighting some games that are improved with Xalia :) Folks took a look at Oddworld: Stranger's Wrath HD (15750) and Xalia has been enabled for that one in the most recent experimental release. We are taking a look at The Takeover too :) Since this PR is already out of date, I hope you don't mind me closing this so you don't need to take the effort to rebase?
> 
> In the future, feel free to also comment on the game-specific github issues in this tracker and tag me and/or @kisak-valve and/or @madewokherd if you notice any games that benefit from enabling Xalia. You can also open issues here if you find any bugs https://github.com/madewokherd/xalia :)
The following working titles are compatible with Xalia:
"35700", # Trine Enchanted Edition
"35720", # Trine 2: Complete Story
"200260", # Batman: Arkham City - Game of the Year Edition

**Comment by jams3223** [comment]
> @vinifmor Thank you for taking an interest in Xalia and highlighting some games that are improved with Xalia :) Folks took a look at Oddworld: Stranger's Wrath HD (15750) and Xalia has been enabled for that one in the most recent experimental release. We are taking a look at The Takeover too :) Since this PR is already out of date, I hope you don't mind me closing this so you don't need to take the effort to rebase?
> 
> In the future, feel free to also comment on the game-specific github issues in this tracker and tag me and/or @kisak-valve and/or @madewokherd if you notice any games that benefit from enabling Xalia. You can also open issues here if you find any bugs https://github.com/madewokherd/xalia :)

@kisak-valve @madewokherd
The following working titles are compatible with Xalia:
"35700", # Trine Enchanted Edition
"35720", # Trine 2: Complete Story
"35140", # Batman: Arkham Asylum Game of the Year Edition
"200260", # Batman: Arkham City - Game of the Year Edition

**Comment by madewokherd** [comment]
Thanks. Trine is proving interesting both because of the PhysX launcher and because it appears to use wxWidgets for its own launcher.

**Comment by madewokherd** [comment]
The Trine launchers have builtin gamepad support so I have to make sure Xalia is disabled for those.

**Comment by jams3223** [comment]
> The Trine launchers have builtin gamepad support so I have to make sure Xalia is disabled for those.

Great!

**Pull request closed without merging**
