### PR TITLE
fix spelling/typo errors

### PR DESCRIPTION
**Pull request by ghost**
small changes to typo spelling errors I spotted while reading source

### CODE REVIEW

**Comment by kisak-valve** [comment]
Hello @sinapis-amicus, you've hinted at multiple spelling issues, but only one change is visible. A github UI issue?

**Comment by ghost** [comment]
> Hello @sinapis-amicus, you've hinted at multiple spelling issues, but only one change is visible. A github UI issue?

I believe so. I corrected more than one typo for sure. I'll look into this as soon as I can. Thanks for the quick feedback @kisak-valve

**Comment by ghost** [comment]
> Hello @sinapis-amicus, you've hinted at multiple spelling issues, but only one change is visible. A github UI issue?

I have confused myself, but I guess there was only one typo in the commits that I made. I know that I made at least two other changes but maybe because they were in submodules like wine or vk3d-proton they weren't visible.

**Comment by kisak-valve** [comment]
If there's a typo in VKD3D-Proton or wine, it would be better to send that to the upstream projects. Any typos that don't break something and exist upstream aren't worth the overhead of tracking downstream.

**Pull request closed without merging**
