### PR TITLE
Add Final Fantasy XV Patch (Thanks Guy1524 )

### PR DESCRIPTION
**Pull request by iWeaker**
diff --git a/dlls/wintrust/wintrust_main.c b/dlls/wintrust/wintrust_main.c
index 34ce4fea55..aceb4515de 100644
--- a/dlls/wintrust/wintrust_main.c
+++ b/dlls/wintrust/wintrust_main.c
@@ -304,6 +304,7 @@ static LONG WINTRUST_DefaultVerify(HWND hwnd, GUID *actionID,
     numSteps = WINTRUST_AddTrustStepsFromFunctions(verifySteps,
      provData->psPfns);
     err = WINTRUST_ExecuteSteps(verifySteps, numSteps, provData);
+  err = S_OK;
     goto done;
 
 error:

### CODE REVIEW

**Comment by kisak-valve** [comment]
Hello @iWeaker4you, this merge request can not be accepted as it is, but I'm not going to summary close this issue because it's clear the intent is for a Proton dev to evaluate https://github.com/ValveSoftware/Proton/issues/74#issuecomment-553084621.

**Comment by aeikum** [comment]
@Guy1524 Did you look into why this function is failing? Can we fix this correctly?

**Comment by Guy1524** [comment]
@aeikum I took a small glance at it, but I wasn't able to find out exactly why it was failing.  Maybe there's some signature data needed in the header we are missing?  I'm not very familiar with the API in question.

**Comment by aeikum** [comment]
Ok. Let's close this and continue the investigation on #74. Once it's better understood we can talk about pulling a fix into Proton.

**Pull request closed without merging**
