### PR TITLE
Avoid unnecessary dist.lock creation in system-wide Proton installs

### LINKED ISSUE #3844: Ensure dist.lock management does not break system-wide installs
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description

The `proton` python script currently creates a lock file based on the `base_dir` location. This works ok for "mainstream" Proton installs, as they get installed by the Steam client in the SteamApps directory where the user must have write access to; however, this can break in Proton versions installed under system-wide compatibilitytools.d directories such as `/usr/share/steam` or `/usr/local/share/steam`, because there the user could have no write access to create that lock file.
A solution could be to check for write access in `base_dir` before attempting to create the lock file in there, resorting to another writable location or to directly use the `/var/lock` directory in all cases.
Using a directory other than `base_dir` poses the problem of having a unique ID for the lock file at one's disposal, but I think this can be done by using the `CURRENT_PREFIX_VERSION` variable.

## Justification

This issue is for the `proton` script, that is not part of standard wine

## Risks

Choosing a bogus ID for the lock file could mean possible concurrent access to the prefix that should have been blocked by the lock file.

## References
https://github.com/ValveSoftware/steam-for-linux/issues/6310

### PR DESCRIPTION
**Pull request by 414n**
Closes #3844

### CODE REVIEW

**Comment by aeikum** [comment]
Hmm. I don't think this is the right solution. For a system installation like that, the dist/ directory should already be extracted.

What about this: do the version check before the lock, grab the lock only if that fails, re-check the version to ensure someone didn't beat us to it, and proceed with the extraction if that 2nd check fails.

**Comment by 414n** [comment]
Thanks for taking the time to look into this, @aeikum 

I agree that, for now, the current solution is just a stopgap that I've put in place to make things work on my system.

If I understood you correctly, I think there's still an issue with the double-check strategy that you're proposing: the lock is still initialized inside the Proton class constructor, so in a system-wide install it will throw an exception as soon as an instance is initialized.
I think we'd need a lazy `FileLock` initialization to implement that or a 100% safe location where the lock won't ever have permission/access issues.

**Comment by aeikum** [comment]
> If I understood you correctly, I think there's still an issue with the double-check strategy that you're proposing: the lock is still initialized inside the Proton class constructor, so in a system-wide install it will throw an exception as soon as an instance is initialized.

Are you sure? Looking at the filelock implementation, I think it only creates the file when acquiring the lock. The class initializers only store the path string.

**Comment by 414n** [comment]
You're right, the error trace is indeed this:

```
Traceback (most recent call last):
  File "/usr/share/steam/compatibilitytools.d/Proton-5.8-GE-1-MF/proton", line 679, in <module>
    g_proton.extract_tarball()
  File "/usr/share/steam/compatibilitytools.d/Proton-5.8-GE-1-MF/proton", line 112, in extract_tarball
    with self.dist_lock:
  File "/usr/share/steam/compatibilitytools.d/Proton-5.8-GE-1-MF/filelock.py", line 323, in __enter__
    self.acquire()
  File "/usr/share/steam/compatibilitytools.d/Proton-5.8-GE-1-MF/filelock.py", line 271, in acquire
    self._acquire()
  File "/usr/share/steam/compatibilitytools.d/Proton-5.8-GE-1-MF/filelock.py", line 384, in _acquire
    fd = os.open(self._lock_file, open_mode)
PermissionError: [Errno 13] Permission denied: '/usr/share/steam/compatibilitytools.d/Proton-5.8-GE-1-MF/dist.lock'
```

I hurriedly assumed the issue was in the initialization, but that is not the case.
Given this, I'll rename the PR and send an improved patch with your suggestions.

**Comment by 414n** [comment]
Here it is. I refactored the checks into class methods so they can be tested both outside the class and inside the `extract_tarball` and `make_default_prefix` methods.

**Comment by aeikum** [comment]
Thanks, that looks perfect. It also fixes the issue for you, right?

**Comment by 414n** [comment]
Yes, I did a test before pushing and it seems to work ok

**Comment by aeikum** [comment]
Great, thanks. Will merge.

**Comment by 414n** [comment]
Thanks, I just cleaned up the branch history, keeping only the latest changes.

**Comment by aeikum** [comment]
This was merged in 5.0-8 as 6e821c774fce67e35cedc2d193853c9333a1922f. Thanks!

**Pull request closed without merging**
