### PR TITLE
Support DirectX 11

### PR DESCRIPTION
**Pull request by niemiecki-agent-tusk**
Hello,
DirectX 11 support for linux would be helpful.

### CODE REVIEW

**Comment by misyltoad** [comment]
DXVK does this and it is already included in Proton.

**Comment by Leopard1907** [comment]
🐸

**Comment by niemiecki-agent-tusk** [comment]
> DXVK does this and it is already included in Proton.

Why does the error display?
"https://imgur.com/njaVe3m"

**Comment by misyltoad** [comment]
You're probably missing a Vulkan driver. Make sure you have both a x64 and x32 one.

**Comment by tannisroot** [comment]
Feel free to join Lutris discord server, I am sure we can help you get the game working: https://discord.gg/Pnt5CuY

**Pull request closed without merging**
