### PR TITLE
Implement mechanism for game-specific tweaks and workarounds (3.16)

### PR DESCRIPTION
**Pull request by dreamer**
Continuation of #1423, rebased to proton_3.16. During rebase I adapted it to new buildsystem and squashed some commits.

In current state following games are affected by tweaks module:

* Call of Duty® (2620)
* STAR WARS™ Jedi Knight - Jedi Academy™ (6020) #1744
* STAR WARS™ Jedi Knight II - Jedi Outcast™ (6030) #1732
* EVE Online (8500) #1223
* Return to Castle Wolfenstein (9010) #542
* Age of Empires® III: Complete Collection (105450) #17
* EverQuest® II Free-To-Play. Your Way.™ (201230)
* Tomb Raider I (224960)
* Tesla Effect: A Tex Murphy Adventure (261510) #1317
* Grand Theft Auto V (271590) #37
* The Entente Gold (285480)
* Order of Battle: World War II (312450)
* Town of Salem (334230) #1191
* Business Tour - Online Multiplayer Board Game (397900) #290
* Dungeons & Darkness (479990)
* Cold Waters (541210)
* Hungry Flame (586970)
* PC Building Simulator (621060)
* D&D Lords of Waterdeep (644390)
* Mirror (644560) #1539
* Changed (814540) #961
* Fox Hime Zero (844930)

### CODE REVIEW

**Comment by liberodark** [comment]
Is a great job but I'm not sure that valve validates this because since it uses their own compatibility system either you find a middle ground be well I do not know what valve will do to correct all that we only need a little tweak

**Comment by felisucoibi** [comment]
I miss thw workarround for age of empires 2, seems easy too.

**Comment by codeman101** [comment]
Sorry for this noob question I just want to make sure I understand this currently. Is this a pull request for adding tweaks to the base code that would fix the games listed above?

**Comment by liberodark** [comment]
> Sorry for this noob question I just want to make sure I understand this currently. Is this a pull request for adding tweaks to the base code that would fix the games listed above?

Yes for add tweaks on Proton

**Comment by dreamer** [comment]
Out of tweaks implemented in this PR, almost all were implemented in Proton by other means:

- corefonts were replaced by Liberation fonts with modified metadata
- PROTON_OLD_GL_STRING covers most games, that needed commandline updated

There's no point to keep this PR in this form for few remaining titles any more.

**Comment by jcrben** [comment]
@dreamer do you know which ones weren't handled? I'm guessing there are open issues to handle those problems.

**Comment by dreamer** [comment]
@jcrben yes, there's still no way to pass parameters to game/rewrite `%command%` out of the box nor an ability to create/edit game's configuration files.

Changed commandline was used for Jedi Knight II and could be used to whitelist e.g. Bioshock 2 Remastered.

Changed commandline and conf rewrite was used for Tomb Raider I.

However, I think Proton devs will deem these two kinds of tweaks as not needed/unnecessary (based on my interaction with them in PRs).

**Comment by aeikum** [comment]
Yeah. We can set up the environment however we like, but actually interfering with how the game chooses to run, like changing their command line or configuration options directly, crosses a line. For the games that need gamma adjustments, we should implement gamma handling in Proton in a way that won't totally screw up the whole desktop. Something similar to the FS hack, or possibly by cooperating with the window manager.

**Pull request closed without merging**
