### PR TITLE
Implement SDK 148 - SteamNetworkingSockets008

### PR DESCRIPTION
**Pull request by stevenlafl**
This addresses https://github.com/ValveSoftware/Proton/issues/2165 where SteamNetworkingSockets008 is not a defined interface. I grabbed SDK 148 where these headers are and implemented them in Proton.

For our purposes of inclusion into main branch, I tested 5.0-7 and it works. A link to that binary: https://github.com/stevenlafl/Proton/releases/tag/proton-5.0-7-sdk148

I also tested on 4.11-13 (Download and code available: https://github.com/stevenlafl/Proton/releases/tag/proton-4.11-13-sdk-148) as this **loads Scrap Mechanic faster**. The game will now make it all the way through and is playable with these changes.

I tested SDK 148 networking and it appears to be flawless, but this implementation may not utilize PollGroups. So:
1. I need some review here to be sure this the correct way to go about things.
2. I may need some help implementing ReceiveMessagesOnPollGroup.

See also: https://github.com/ValveSoftware/Proton/issues/3747#issuecomment-611539352

### CODE REVIEW

**Comment by Friz64** [comment]
You probably didn't mean to create that `.vscode` directory

**Comment by stevenlafl** [comment]
> You probably didn't mean to create that `.vscode` directory

Fixed. Also noticed changes to git submodules were added accidentally as I cherry-picked from local, so I re-applied it without them and force pushed over this one.

**Comment by aeikum** [comment]
Hey @stevenlafl! Thanks for working on this. Just wanted to drop you a note that I've seen this and will take a closer look soon. I'm heads-down on some other stuff and don't want to interrupt that just yet, but reviewing your work here is high up on my todo list.

**Comment by aeikum** [comment]
Hi again @stevenlafl . I've just pushed 5.0-8-rc1 public (see #3932) which contains support for SteamNetworkingSockets004 and SteamNetworkingSockets008. Valve messed up the versioning pretty bad between 002 and 004, but I got it sorted out and I think is accurate now in our bridge. Please give the RC a shot and see if it is working well for you.

Note that some games (Gwent and One Piece 4 in our testing) reported failures on this interface, but the real problem actually lies elsewhere.

**Comment by aeikum** [comment]
I implemented it differently, but SteamNetworkingSockets008 is supported now in 5.0-8. Our testing showed many of the affected games still don't work for unrelated reasons, though.

**Pull request closed without merging**
