### PR TITLE
add bison 3.0.4 to proton build

### PR DESCRIPTION
**Pull request by GloriousEggroll**
solves https://github.com/ValveSoftware/Proton/issues/2742

### CODE REVIEW

**Comment by aeikum** [comment]
Thanks! I didn't review the Makefile changes in depth, but we definitely want to be using a submodule, not importing the source directly. http://savannah.gnu.org/git/?group=bison

**Comment by GloriousEggroll** [comment]
Not a problem, corrected the PR, added 3.0.4 as a submodule. Don't mind the name change, I added the new commits from my work machine.

**Comment by GloriousEggroll** [comment]
I've noticed when using bison from git, you must run ./bootstrap before configuring, also even after bootstrapping I still ran into some errors I wasn't able to troubleshoot that were not present in the tarball. Tarballed version worked fine :/

**Comment by aeikum** [comment]
Thanks. I'll probably let this sit until we begin work on the next Wine upgrade, and review it then.

**Comment by aeikum** [comment]
Hey @GloriousEggroll, I ended up going back to using a tarball, because generating those files is pretty tough. Instead of adding the files to repo, I just download the tarball at build-time. You can check out the changes I made here: https://github.com/aeikum/Proton/tree/proton_4.2-bison

I left your authorship on the commit, since the bulk of the work is yours. If you'd like me to change it in any way, let me know.

**Comment by aeikum** [comment]
This was added for the 4.11 build as d7819c7bc5489b4e30c3b0782ccde78c5cd41cd8. Thanks!

**Pull request closed without merging**
