### PR TITLE
Proton isn't in beta version of steam client anymore

### PR DESCRIPTION
**Pull request by Weirdo1312**

### CODE REVIEW

**Comment by aeikum** [comment]
Hey, thanks for the suggestion. It is still the case that sometimes new features and fixes get enabled in the Steam Beta Client first, so I think we should leave the note as it is.

**Comment by arrowgent** [comment]
as how software goes, wine/proton is constantly improving.

its also fairly stable for many titles.

however, i think only proton-experimental is considered a "beta" release

while i understand that SteamPlay Beta Proton-Beta releases are pre-releases prior to being stable.

**Comment by Ruedii** [comment]
I don't think Steam Beta is running separate Steam Runtime anymore.  

So, it might be good to remove most of this.

Probably replace this with:
"*Please note that Proton compatibility is still considered a Beta feature of Steam and may have noticeable bugs and limitations.  Occasionally certain features may initially require the Beta version of Steam."

**Comment by ivyl** [comment]
Hi. This section was removed in the recent README rewrite. It's already in experimental and will be pushed to 6.3 upon next release.

**Pull request closed without merging**
