### PR TITLE
Made glslang as git submodule

### PR DESCRIPTION
**Pull request by 3t0n**
Removed precompiled glslang, added submodule to fix cross build: https://github.com/ValveSoftware/Proton/issues/29 (https://github.com/ValveSoftware/Proton/issues/121), https://github.com/ValveSoftware/Proton/issues/2#issuecomment-415057704.
Updated README for MacOS and added basic manual run info.

Tested on MacOS High Sierra only, increases build time by ~30 sec.

### CODE REVIEW

**Comment by kergoth** [comment]
As glslang is used by the dxvk build, which is done on the host, do we really need both 32 and 64 bit builds of it? We only had one before switching to a submodule, after all.

**Comment by kergoth** [comment]
Off-topic, but just as an FYI, as your fork doesn't allow opening of issues :), your pre-built proton release tarball's dinput.dll.so has a hardcoded reference to the full path on your disk to libSDL-2.0.dylib, which prevents dinput.dll.so from loading into wine. It should be changed to use @rpath/libSDL.dylib or similar to align with its location next to the wine libraries. No idea how to hook that into the build process properly, though. I just fixed it manually with `install_name_tool`.

**Edit**: Looks like it should be trivial to correct the dinput issue in build_proton.sh, I'll prep a separate pull req for that.

**Comment by 3t0n** [comment]
Yes, you are right. 
I simple did it by template in the build script, it easily to change if someone request.
Also, it possible to reuse glslang from MoltenVK for MacOS only.

**Comment by 3t0n** [comment]
Thank you, I'll see what can do!

**Comment by kergoth** [comment]
https://github.com/ValveSoftware/Proton/compare/proton_3.7...kergoth:osx-fixups may be of interest. Rebased a few of my local fixes on top of your branch, and merged your glslang commits, since the conversion to mac was superceded by the switch to a submodule.

**Comment by kergoth** [comment]
https://github.com/wine-mirror/wine/commit/565c2dcf2aef1a555ff1025f230b4708df24d311 might be needed as well, at least my build failed without it. Did you run into that one? Of course that'd have to go in https://github.com/ValveSoftware/wine first.

**Comment by 3t0n** [comment]
Yes, they need to update with new wine to fix build https://github.com/ValveSoftware/wine/issues/4.

**Comment by kergoth** [comment]
OT (is there a reddit or something to discuss proton on the mac? :) but could be useful: just create a  non-steam game in the mac steam client and point it to run-proton from https://gist.github.com/kergoth/5ad792c01fa7200e9eaaa7d920c4daf3 and set launch options to something like '-a 2200 quake3.exe', where 2200 is the steam appid.

It gets your list of steam libraries and searches them for the game, so you can add a library to hold the windows games as you would in linux. See the usage info for details. It can manually run executables from elsewhere with or without -a, and has an option to run proton's wine directly as a convenience to run e.g. winecfg or regedit. It also sets `STEAM_COMPAT_CLIENT_INSTALL_PATH` so proton will copy the steam dlls to connect to the mac client, and works around a dll search issue I ran into with quake 3 where it couldn't find the ones in the steam install directory.

**Comment by ivyl** [comment]
Closing since support for MacOS was dropped.

**Pull request closed without merging**
