### PR TITLE
Update CURRENT_PREFIX_VERSION to latest

### PR DESCRIPTION
**Pull request by Zlopez**
I noticed that this constant wasn't changed with latest release, so here is a patch for it.

### CODE REVIEW

**Comment by Plagman** [comment]
I think we only need to change this when necessary, eg. if the prefix structure or contents changes in incompatible ways.

**Comment by Zlopez** [comment]
Strange, the games are still using the 4.2-1, till I change this manually. I noticed the same behavior on 3.16-8, when the games still used 3.16-1.

**Comment by Zlopez** [comment]
It looks like I was wrong, I tried one game today with `PROTON_LOG=1` and the version used was `4.2-2`.

I was just confused that I didn't saw this message when I started the game after update from `4.2-1` to `4.2-2` `log("Upgrading prefix from " + str(old_ver) + " to " + CURRENT_PREFIX_VERSION + " (" + os.environ["STEAM_COMPAT_DATA_PATH"] + ")")`

**Comment by aeikum** [comment]
Yeah @Plagman is right. This is the "prefix version" which is separate from the "Proton version." We bump it when we need to do something special when changing to a new Proton version.

**Pull request closed without merging**
