### PR TITLE
Update PREREQS.md

### PR DESCRIPTION
**Pull request by dweipert-3138720606**
This is what I get when I search for nvidia-driver packages.

```
❯ sudo apt-cache search nvidia-driver
nvidia-304-updates - Transitional package for nvidia-304
nvidia-361 - Transitional package for nvidia-367
nvidia-384 - NVIDIA binary driver - version 384.130
nvidia-304 - NVIDIA legacy binary driver - version 304.137
nvidia-340 - NVIDIA binary driver - version 340.107
nvidia-390 - NVIDIA binary driver - version 390.77
nvidia-396 - NVIDIA binary driver - version 396.54
```

### CODE REVIEW

**Comment by aeikum** [comment]
What distribution are you using?

**Comment by dweipert-3138720606** [comment]
I'm using Ubuntu 16.04. I just tested it with 18.04 and there the package `nvidia-driver-396` does exist.

**Comment by DanMan** [comment]
That description belongs in the wiki instead, no?

**Comment by ghost** [comment]
@DanMan the README has apt install package names. Would be nice to have it be accurate.

@aeikum I have the same package names on Ubuntu 18.04

**Comment by mati865** [comment]
Ubuntu 16.04 and 18.04 have different naming schemes. To avoid confusion it could be formatted like that:
```
sudo add-apt-repository ppa:graphics-drivers/ppa

# For Ubuntu 18.04 or later:
sudo apt install nvidia-driver-396 

# For Ubuntu 16.04:
sudo apt install nvidia-396
```

**Pull request closed without merging**
