### PR TITLE
Fix stdcall parameter size computation

### PR DESCRIPTION
**Pull request by mrexodia**
The size of each parameter has to be rounded up to a multiple of 4 (register size) before adding them together.

### CODE REVIEW

**Comment by nsivov** [comment]
This looks correct in principle I think, it would be nicer if it wasn't using floating pointing truncation though. But argument sizes should only be important if you're building with MSVC or cross compile mingw-w64, is that your use case?

**Comment by mrexodia** [comment]
I tried writing it with some helper function to round up to the nearest 4, but in my opinion the `math.ceil` makes it much clearer what's going on. In my case I encountered this issue when compiling with mingw-w64 (32 bit target) on Windows (without wine, the rest of the code is also pretty modified). It's just an issue I noticed and I wanted to contribute back upstream.

**Comment by nsivov** [comment]
I think it's valid, and should be fixed, thanks for the patch.

**Comment by nsivov** [comment]
This was merged as Valvesoftware/Proton@01c0124.

**Pull request closed without merging**
